# Exploratory Data Analysis

> Understanding the dataset to explore how the data is present in the database and if there is a need of creating aggregates tables that can help use with:

- Vendor selection for profitability
- Product pricing optimization

In [1]:
import pandas as pd
import sqlite3

In [2]:
#creating a database connection
con = sqlite3.connect('inventory.db')

#Checking the tables in the database
tables = pd.read_sql_query("Select name from sqlite_master where type='table'", con)
print(tables)

                   name
0       begin_inventory
1         end_inventory
2             purchases
3       purchase_prices
4                 sales
5        vendor_invoice
6  vendor_sales_summary

In [3]:
for i in tables['name']:
    print('-'*50, f'{i}','-'*50)
    print('Count of records:', pd.read_sql(f"select count(*) as count from {i}", con)['count'].values[0])
    display(pd.read_sql(f"select * from {i} limit 5", con))

-------------------------------------------------- begin_inventory --------------------------------------------------
Count of records: 206529

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

-------------------------------------------------- end_inventory --------------------------------------------------
Count of records: 224489

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

-------------------------------------------------- purchases --------------------------------------------------
Count of records: 2372474

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

-------------------------------------------------- purchase_prices --------------------------------------------------
Count of records: 12261

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

-------------------------------------------------- sales --------------------------------------------------
Count of records: 12825363

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

-------------------------------------------------- vendor_invoice --------------------------------------------------
Count of records: 5543

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

-------------------------------------------------- vendor_sales_summary --------------------------------------------------
Count of records: 10692

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseAmount,TotalSalesQuantity,TotalSalesAmount,TotalSalesPrice,TotalExciseTax,TotalFreightCost,GrossProfit,ProfitMargin,StockTurnover,TotalPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080,3811251.60,142049.0,5101919.51,672819.31,260999.20,68601.68,1290667.91,25.297693,0.979108,1.338647
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038,3804041.22,160247.0,4819073.49,561512.37,294438.66,144929.24,1015032.27,21.062810,0.976890,1.266830
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407,3418303.68,187140.0,4538120.60,461140.15,343854.07,123780.22,1119816.92,24.675786,0.998575,1.327594
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682,3261197.94,200412.0,4475972.88,420050.01,368242.80,257032.07,1214774.94,27.139908,0.993703,1.372493
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,138109,3023206.01,135838.0,4223107.62,545778.28,249587.83,257032.07,1199901.61,28.412764,0.983556,1.396897

In [4]:
purchases = pd.read_sql('select * from purchases Where VendorNumber = 480', con)
purchases

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,5_SUTTON_3348,5,3348,Bombay Sapphire Gin,1.75L,480,BACARDI USA INC,8106,2023-12-20,2024-01-02,2024-01-12,2024-02-05,22.38,6,134.28,1
1,1_HARDERSFIELD_8358,1,8358,Bacardi 151 Proof,750mL,480,BACARDI USA INC,8106,2023-12-20,2024-01-01,2024-01-12,2024-02-05,14.49,12,173.88,1
2,30_CULCHETH_4903,30,4903,Bacardi Superior Rum,200mL,480,BACARDI USA INC,8106,2023-12-20,2024-01-01,2024-01-12,2024-02-05,2.87,48,137.76,1
3,34_PITMERDEN_3782,34,3782,Grey Goose Le Citron Vodka,750mL,480,BACARDI USA INC,8106,2023-12-20,2024-01-02,2024-01-12,2024-02-05,18.89,5,94.45,1
4,1_HARDERSFIELD_4233,1,4233,Castillo Silver Label Rum,1.75L,480,BACARDI USA INC,8106,2023-12-20,2024-01-01,2024-01-12,2024-02-05,7.87,23,181.01,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91841,40_BULLMAR_5315,40,5315,B & B Liqueur Dom,750mL,480,BACARDI USA INC,13641,2024-12-23,2024-12-27,2025-01-10,2025-02-14,19.22,12,230.64,1
91842,36_LEWES_3857,36,3857,Grey Goose Vodka,1.75L,480,BACARDI USA INC,13641,2024-12-23,2024-12-29,2025-01-10,2025-02-14,38.27,6,229.62,1
91843,23_ARBINGTON_4267,23,4267,Bacardi Limon Rum,1.75L,480,BACARDI USA INC,13641,2024-12-23,2024-12-29,2025-01-10,2025-02-14,15.62,6,93.72,1
91844,58_HARTLEPOOL_3857,58,3857,Grey Goose Vodka,1.75L,480,BACARDI USA INC,13641,2024-12-23,2024-12-27,2025-01-10,2025-02-14,38.27,6,229.62,1
91845,38_GOULCREST_4233,38,4233,Castillo Silver Label Rum,1.75L,480,BACARDI USA INC,13641,2024-12-23,2024-12-26,2025-01-10,2025-02-14,7.87,18,141.66,1

In [5]:
purchase_price = pd.read_sql('select * from purchase_prices Where VendorNumber = 480', con)
purchase_price

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,126,Grey Goose Vodka,32.99,1000mL,1000,1,20.14,480,BACARDI USA INC
1,443,St Germain Liqueur,33.99,750mL,750,1,24.45,480,BACARDI USA INC
2,508,Bacardi Superior Rum,12.99,1000mL,1000,1,9.77,480,BACARDI USA INC
3,743,Angels Envy Whiskey,45.99,750mL,750,1,36.50,480,BACARDI USA INC
4,802,Bacardi Torched Cherry Rum,11.99,750mL,750,1,7.99,480,BACARDI USA INC
...,...,...,...,...,...,...,...,...,...
179,4024,Bacardi Razz,0.99,50mL,50,1,0.71,480,BACARDI USA INC
180,4192,Havana Club Anejo Blanco Rum,19.99,750mL,750,1,15.03,480,BACARDI USA INC
181,4216,Havana Club Anejo Clsco Gold,21.99,750mL,750,1,16.92,480,BACARDI USA INC
182,4237,Havana Club Anejo Blanco Rum,0.99,50mL,50,1,0.76,480,BACARDI USA INC
183,4251,Havana Club Anejo Clsco Gold,0.99,50mL,50,1,0.78,480,BACARDI USA INC

In [6]:
sales = pd.read_sql('select * from sales Where VendorNo = 480', con)
sales

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1020,1,1020,B & B Dom VAP,750mL,1,24.99,24.99,2024-01-29,750.0,1,0.79,480,BACARDI USA INC
1,1_HARDERSFIELD_12191,1,12191,M & R Sparkling Rose,750mL,1,9.99,9.99,2024-01-01,750.0,2,0.11,480,BACARDI USA INC
2,1_HARDERSFIELD_12191,1,12191,M & R Sparkling Rose,750mL,1,9.99,9.99,2024-01-07,750.0,2,0.11,480,BACARDI USA INC
3,1_HARDERSFIELD_12191,1,12191,M & R Sparkling Rose,750mL,1,9.99,9.99,2024-01-16,750.0,2,0.11,480,BACARDI USA INC
4,1_HARDERSFIELD_12191,1,12191,M & R Sparkling Rose,750mL,1,9.99,9.99,2024-01-28,750.0,2,0.11,480,BACARDI USA INC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539467,9_BLACKPOOL_903,9,903,Bombay Sapphire Gin,Liter,2,55.98,27.99,2024-12-24,1000.0,1,2.10,480,BACARDI USA INC
539468,9_BLACKPOOL_903,9,903,Bombay Sapphire Gin,Liter,1,27.99,27.99,2024-12-27,1000.0,1,1.05,480,BACARDI USA INC
539469,9_BLACKPOOL_903,9,903,Bombay Sapphire Gin,Liter,1,27.99,27.99,2024-12-29,1000.0,1,1.05,480,BACARDI USA INC
539470,9_BLACKPOOL_903,9,903,Bombay Sapphire Gin,Liter,1,27.99,27.99,2024-12-30,1000.0,1,1.05,480,BACARDI USA INC
539471,9_BLACKPOOL_903,9,903,Bombay Sapphire Gin,Liter,1,27.99,27.99,2024-12-31,1000.0,1,1.05,480,BACARDI USA INC

In [7]:
vendor_invoice = pd.read_sql('select * from vendor_invoice Where VendorNumber = 480', con)
vendor_invoice

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,NaN
1,480,BACARDI USA INC,2024-01-19,8288,2024-01-01,2024-02-18,32463,396606.13,1864.05,Frank Delahunt
2,480,BACARDI USA INC,2024-01-22,8308,2024-01-03,2024-02-26,15033,173408.47,832.36,NaN
3,480,BACARDI USA INC,2024-01-29,8433,2024-01-12,2024-03-10,16160,150950.37,815.13,NaN
4,480,BACARDI USA INC,2024-02-02,8548,2024-01-20,2024-03-19,20647,215769.02,1165.15,NaN
5,480,BACARDI USA INC,2024-02-16,8618,2024-01-25,2024-03-17,19253,227503.57,1205.77,NaN
6,480,BACARDI USA INC,2024-02-23,8719,2024-02-01,2024-03-24,15365,163835.98,802.80,NaN
7,480,BACARDI USA INC,2024-03-01,8877,2024-02-11,2024-04-08,15297,172888.12,778.00,NaN
8,480,BACARDI USA INC,2024-03-06,8914,2024-02-14,2024-04-04,13341,148069.14,695.92,NaN
9,480,BACARDI USA INC,2024-03-15,9062,2024-02-24,2024-04-24,12618,137129.12,699.36,NaN
10,480,BACARDI USA INC,2024-03-17,9113,2024-02-28,2024-05-01,12843,145436.94,741.73,NaN
11,480,BACARDI USA INC,2024-03-23,9213,2024-03-06,2024-04-24,13411,131921.07,712.37,NaN
12,480,BACARDI USA INC,2024-04-02,9389,2024-03-18,2024-04-30,12719,137470.25,714.85,NaN
13,480,BACARDI USA INC,2024-04-06,9415,2024-03-20,2024-05-14,19525,252445.47,1262.23,Frank Delahunt
14,480,BACARDI USA INC,2024-04-16,9533,2024-03-28,2024-05-12,17537,219952.32,1055.77,NaN
15,480,BACARDI USA INC,2024-04-20,9658,2024-04-05,2024-05-30,16607,198302.71,1051.00,NaN
16,480,BACARDI USA INC,2024-04-30,9738,2024-04-11,2024-05-26,21648,257338.55,1209.49,Frank Delahunt
17,480,BACARDI USA INC,2024-05-07,9847,2024-04-19,2024-06-13,23002,295393.87,1358.81,Frank Delahunt
18,480,BACARDI USA INC,2024-05-16,9929,2024-04-25,2024-06-20,22553,298053.75,1341.24,Frank Delahunt
19,480,BACARDI USA INC,2024-05-18,10022,2024-05-01,2024-06-28,21903,274587.75,1400.40,Frank Delahunt
20,480,BACARDI USA INC,2024-05-30,10187,2024-05-12,2024-07-07,21871,271328.78,1410.91,Frank Delahunt
21,480,BACARDI USA INC,2024-05-31,10240,2024-05-16,2024-07-16,32991,485190.90,2620.03,Frank Delahunt
22,480,BACARDI USA INC,2024-06-12,10325,2024-05-22,2024-07-13,45168,622937.67,3114.69,Frank Delahunt
23,480,BACARDI USA INC,2024-06-14,10497,2024-06-02,2024-07-28,38503,546728.80,3007.01,Frank Delahunt
24,480,BACARDI USA INC,2024-06-27,10550,2024-06-06,2024-08-05,33594,435940.79,2048.92,Frank Delahunt
25,480,BACARDI USA INC,2024-07-04,10665,2024-06-14,2024-08-12,49452,400799.37,1923.84,Frank Delahunt
26,480,BACARDI USA INC,2024-07-09,10778,2024-06-22,2024-08-04,28926,395672.81,1899.23,Frank Delahunt
27,480,BACARDI USA INC,2024-07-05,10837,2024-06-25,2024-08-12,6718,94479.04,434.60,NaN
28,480,BACARDI USA INC,2024-07-14,10999,2024-07-01,2024-08-18,45585,614734.81,3012.20,Frank Delahunt
29,480,BACARDI USA INC,2024-07-24,11067,2024-07-05,2024-08-24,48407,653537.89,3071.63,Frank Delahunt
30,480,BACARDI USA INC,2024-08-01,11188,2024-07-14,2024-09-09,58643,792646.81,3804.70,Frank Delahunt
31,480,BACARDI USA INC,2024-08-02,11262,2024-07-19,2024-09-17,49827,722550.39,3612.75,Frank Delahunt
32,480,BACARDI USA INC,2024-08-11,11341,2024-07-25,2024-09-15,25877,345721.85,1590.32,Frank Delahunt
33,480,BACARDI USA INC,2024-08-17,11491,2024-08-04,2024-09-20,26238,316219.81,1454.61,Frank Delahunt
34,480,BACARDI USA INC,2024-08-28,11606,2024-08-11,2024-10-01,33725,418579.14,1967.32,Frank Delahunt
35,480,BACARDI USA INC,2024-09-01,11686,2024-08-17,2024-10-07,21541,261170.36,1253.62,Frank Delahunt
36,480,BACARDI USA INC,2024-09-06,11748,2024-08-22,2024-10-09,22317,253169.40,1265.85,Frank Delahunt
37,480,BACARDI USA INC,2024-09-20,11859,2024-08-30,2024-10-22,22405,267009.84,1415.15,Frank Delahunt
38,480,BACARDI USA INC,2024-09-20,12025,2024-09-09,2024-10-30,23219,200556.68,942.62,NaN
39,480,BACARDI USA INC,2024-10-03,12040,2024-09-11,2024-10-27,20000,236103.42,1133.30,NaN
40,480,BACARDI USA INC,2024-10-07,12236,2024-09-23,2024-11-10,39981,457183.53,2514.51,Frank Delahunt
41,480,BACARDI USA INC,2024-10-05,12254,2024-09-23,2024-11-13,264,4403.92,22.90,NaN
42,480,BACARDI USA INC,2024-10-16,12362,2024-09-28,2024-11-14,25279,317797.37,1430.09,Frank Delahunt
43,480,BACARDI USA INC,2024-10-19,12503,2024-10-07,2024-11-19,22284,290327.82,1364.54,Frank Delahunt
44,480,BACARDI USA INC,2024-10-25,12538,2024-10-10,2024-11-30,21735,289867.95,1594.27,Frank Delahunt
45,480,BACARDI USA INC,2024-11-06,12635,2024-10-17,2024-12-02,32736,474904.53,2374.52,Frank Delahunt
46,480,BACARDI USA INC,2024-11-12,12766,2024-10-26,2024-12-19,31929,461855.78,2355.46,Frank Delahunt
47,480,BACARDI USA INC,2024-11-17,12890,2024-11-02,2024-12-29,40775,574958.37,3047.28,Frank Delahunt
48,480,BACARDI USA INC,2024-11-26,12946,2024-11-07,2024-12-28,32203,400311.97,1801.40,Frank Delahunt
49,480,BACARDI USA INC,2024-11-30,13093,2024-11-16,2025-01-15,23079,262474.83,1233.63,Frank Delahunt
50,480,BACARDI USA INC,2024-12-06,13220,2024-11-25,2025-01-11,31602,364837.70,1787.70,Frank Delahunt
51,480,BACARDI USA INC,2024-12-15,13238,2024-11-27,2025-01-13,26278,290684.67,1308.08,Frank Delahunt
52,480,BACARDI USA INC,2024-12-26,13350,2024-12-05,2025-01-20,30183,325820.26,1694.27,Frank Delahunt
53,480,BACARDI USA INC,2025-01-03,13446,2024-12-11,2025-02-06,30898,317094.31,1553.76,Frank Delahunt
54,480,BACARDI USA INC,2025-01-08,13628,2024-12-22,2025-02-03,30817,322230.77,1578.93,Frank Delahunt

> The purchases table contains actual purchase data, including the date of purchase, products (brands) purchased by vendors, the amount paid (in dollars), and the quantity purchased.

> The purchase price column is derived from the purchase_prices table, which provides product-wise actual and purchase prices. The combination of vendor and brand is unique in this table.

> The vendor_invoice table aggregates data from the purchases table, summarizing quantity and dollar amounts, along with an additional column for freight. This table maintains uniqueness based on vendor and PO number.

> The sales table captures actual sales transactions, detailing the brands purchased by vendors, the quantity sold, the selling price, and the revenue earned.

### As the data that we need for analysis is distributed in different tables, we need to create a summary table containing:

- purchase transactions made by vendors
- sales transaction data
- freight costs for each vendor
- actual product prices from vendors

In [8]:
vendor_invoice.columns

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='str')

In [9]:
freight_summary =  pd.read_sql_query("""select 
VendorNumber, 
SUM(Freight) as TotalFreightCost 
From vendor_invoice
group by VendorNumber""", con)
freight_summary

     VendorNumber  TotalFreightCost
0               2             27.08
1              54              0.48
2              60            367.52
3             105             62.39
4             200              6.19
..            ...               ...
121         98450            856.02
122         99166            130.09
123        172662            178.34
124        173357            202.50
125        201359              0.09

[126 rows x 2 columns]

In [10]:
purchase_price.columns

Index(['Brand', 'Description', 'Price', 'Size', 'Volume', 'Classification',
       'PurchasePrice', 'VendorNumber', 'VendorName'],
      dtype='str')

In [11]:
purchases.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'VendorNumber',
       'VendorName', 'PONumber', 'PODate', 'ReceivingDate', 'InvoiceDate',
       'PayDate', 'PurchasePrice', 'Quantity', 'Dollars', 'Classification'],
      dtype='str')

In [12]:
pd.read_sql_query("""Select
p.VendorNumber,
p.VendorName,
p.Brand,
p.PurchasePrice,
pp.Volume,
pp.Price as ActualPrice,
SUM(p.Quantity) as TotalPurchasedQuantity,
SUM(p.Dollars) as TotalPurchaseAmount
From purchases p
Join purchase_prices pp
On p.Brand  = pp.Brand
Where p.PurchasePrice > 0
Group by p.VendorNumber, p.VendorName, p.Brand   
Order by TotalPurchaseAmount          
""", con)

,VendorNumber,VendorName,Brand,PurchasePrice,Volume,ActualPrice,TotalPurchasedQuantity,TotalPurchaseAmount
0,7245,PROXIMO SPIRITS INC.,3065,0.71,50,0.99,1,0.71
1,3960,DIAGEO NORTH AMERICA INC,6127,1.47,200,1.99,1,1.47
2,3924,HEAVEN HILL DISTILLERIES,9123,0.74,50,0.99,2,1.48
3,8004,SAZERAC CO INC,5683,0.39,50,0.49,6,2.34
4,9815,WINE GROUP INC,8527,1.32,750,4.99,2,2.64
...,...,...,...,...,...,...,...,...
10687,3960,DIAGEO NORTH AMERICA INC,3545,21.89,1750,29.99,138109,3023206.01
10688,3960,DIAGEO NORTH AMERICA INC,4261,16.17,1750,22.99,201682,3261197.94
10689,17035,PERNOD RICARD USA,8068,18.24,1750,24.99,187407,3418303.68
10690,4425,MARTIGNETTI COMPANIES,3405,23.19,1750,28.99,164038,3804041.22
10691,1128,BROWN-FORMAN CORP,1233,26.27,1750,36.99,145080,3811251.60

In [13]:
sales.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName'],
      dtype='str')

In [14]:
pd.read_sql_query("""Select
VendorNo,
Brand,
SUM(SalesQuantity) as TotalSalesQuantity,
SUM(SalesDollars) as TotalSalesAmount,
SUM(SalesPrice) as TotalSalesPrice,
SUM(ExciseTax) as TotalExciseTax
From sales
Group by VendorNo, Brand
Order by TotalSalesAmount DESC""", con)

,VendorNo,Brand,TotalSalesQuantity,TotalSalesAmount,TotalSalesPrice,TotalExciseTax
0,1128,1233,142049,5101919.51,672819.31,260999.20
1,4425,3405,160247,4819073.49,561512.37,294438.66
2,17035,8068,187140,4538120.60,461140.15,343854.07
3,3960,4261,200412,4475972.88,420050.01,368242.80
4,3960,3545,135838,4223107.62,545778.28,249587.83
...,...,...,...,...,...,...
11267,3252,3933,2,1.98,0.99,0.10
11268,3924,9123,2,1.98,0.99,0.10
11269,10050,3623,2,1.98,1.98,0.10
11270,9206,2773,1,0.99,0.99,0.05
11271,8004,5287,2,0.98,0.98,0.10

In [15]:
vendor_sales_summary = pd.read_sql_query("""
WITH FreightSummary AS 
(
    SELECT 
        VendorNumber, 
        SUM(Freight) as TotalFreightCost 
    FROM vendor_invoice
    GROUP BY VendorNumber
),

purchase_summary AS 
(
    SELECT
        p.VendorNumber,
        p.VendorName,
        p.Brand,
        p.Description,
        p.PurchasePrice,
        pp.Volume,
        pp.Price as ActualPrice,
        SUM(p.Quantity) as TotalPurchaseQuantity,
        SUM(p.Dollars) as TotalPurchaseAmount
    FROM purchases p
    JOIN purchase_prices pp
        ON p.Brand = pp.Brand
    WHERE p.PurchasePrice > 0
    GROUP BY 
        p.VendorNumber, p.VendorName, p.Brand, 
        p.Description, p.PurchasePrice, 
        pp.Volume, pp.Price
),

Sales_Summary AS 
(
    SELECT
        VendorNo,
        Brand,
        SUM(SalesQuantity) as TotalSalesQuantity,
        SUM(SalesDollars) as TotalSalesAmount,
        SUM(SalesPrice) as TotalSalesPrice,
        SUM(ExciseTax) as TotalExciseTax
    FROM sales
    GROUP BY VendorNo, Brand
)

SELECT
    ps.VendorNumber,
    ps.VendorName,
    ps.Brand,
    ps.Description,
    ps.PurchasePrice,
    ps.ActualPrice,
    ps.Volume,
    ps.TotalPurchaseQuantity,
    ps.TotalPurchaseAmount,

    ss.TotalSalesQuantity,
    ss.TotalSalesAmount,
    ss.TotalSalesPrice,
    ss.TotalExciseTax,

    fs.TotalFreightCost

FROM purchase_summary ps

LEFT JOIN Sales_Summary ss
    ON ps.VendorNumber = ss.VendorNo
    AND ps.Brand = ss.Brand

LEFT JOIN FreightSummary fs
    ON ps.VendorNumber = fs.VendorNumber

ORDER BY ps.TotalPurchaseAmount DESC
""", con)

In [16]:
vendor_sales_summary

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseAmount,TotalSalesQuantity,TotalSalesAmount,TotalSalesPrice,TotalExciseTax,TotalFreightCost
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750,145080,3811251.60,142049.0,5101919.51,672819.31,260999.20,68601.68
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750,164038,3804041.22,160247.0,4819073.49,561512.37,294438.66,144929.24
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750,187407,3418303.68,187140.0,4538120.60,461140.15,343854.07,123780.22
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750,201682,3261197.94,200412.0,4475972.88,420050.01,368242.80,257032.07
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750,138109,3023206.01,135838.0,4223107.62,545778.28,249587.83,257032.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,4.99,750,2,2.64,5.0,15.95,10.96,0.55,27100.41
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,0.49,50,6,2.34,134.0,65.66,1.47,7.04,50293.62
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.74,0.99,50,2,1.48,2.0,1.98,0.99,0.10,14069.87
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.47,1.99,200,1,1.47,72.0,143.28,77.61,15.12,257032.07
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,0.99,50,1,0.71,86.0,85.14,33.66,4.46,38994.78

This query generates a Vendor-wise summary which is valuable for:

>Performance Optimization:

- The query involves heavy joins and aggregrations on large datasets like sales and purchases.
- Storing the Pre-aggregated results avoids repeated expensive computations.
- Helps analyzing sales, purchase and pricing for different vendors and brands.
- Future benefits of storing this data for dashboarding and reporting.
- Instead of running expensive queries each time, dashboards can fetch data from vendor_sales_summary.

In [17]:
vendor_sales_summary.dtypes
#Checking the data types

VendorNumber               int64
VendorName                   str
Brand                      int64
Description                  str
PurchasePrice            float64
ActualPrice              float64
Volume                       str
TotalPurchaseQuantity      int64
TotalPurchaseAmount      float64
TotalSalesQuantity       float64
TotalSalesAmount         float64
TotalSalesPrice          float64
TotalExciseTax           float64
TotalFreightCost         float64
dtype: object

In [18]:
vendor_sales_summary.isnull().sum()
#Checking the null values

VendorNumber               0
VendorName                 0
Brand                      0
Description                0
PurchasePrice              0
ActualPrice                0
Volume                     0
TotalPurchaseQuantity      0
TotalPurchaseAmount        0
TotalSalesQuantity       178
TotalSalesAmount         178
TotalSalesPrice          178
TotalExciseTax           178
TotalFreightCost           0
dtype: int64

In [19]:
vendor_sales_summary['VendorName'].unique
#Checking the inconsistiencies in the Names like wide spaces

<bound method Series.unique of 0        BROWN-FORMAN CORP
1              MARTIGNETTI COMPANIES
2        PERNOD RICARD USA
3        DIAGEO NORTH AMERICA INC
4        DIAGEO NORTH AMERICA INC
                    ...
10687    WINE GROUP INC
10688    SAZERAC CO INC
10689    HEAVEN HILL DISTILLERIES
10690    DIAGEO NORTH AMERICA INC
10691    PROXIMO SPIRITS INC.
Name: VendorName, Length: 10692, dtype: str>

In [20]:
vendor_sales_summary['Volume'] = vendor_sales_summary['Volume'].astype('float64')
#Changing the data type of Volume Column from int to float

In [21]:
vendor_sales_summary.fillna(0, inplace = True)
#Replacing the null values with 0

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseAmount,TotalSalesQuantity,TotalSalesAmount,TotalSalesPrice,TotalExciseTax,TotalFreightCost
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080,3811251.60,142049.0,5101919.51,672819.31,260999.20,68601.68
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038,3804041.22,160247.0,4819073.49,561512.37,294438.66,144929.24
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407,3418303.68,187140.0,4538120.60,461140.15,343854.07,123780.22
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682,3261197.94,200412.0,4475972.88,420050.01,368242.80,257032.07
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,138109,3023206.01,135838.0,4223107.62,545778.28,249587.83,257032.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,4.99,750.0,2,2.64,5.0,15.95,10.96,0.55,27100.41
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,0.49,50.0,6,2.34,134.0,65.66,1.47,7.04,50293.62
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.74,0.99,50.0,2,1.48,2.0,1.98,0.99,0.10,14069.87
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.47,1.99,200.0,1,1.47,72.0,143.28,77.61,15.12,257032.07
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,0.99,50.0,1,0.71,86.0,85.14,33.66,4.46,38994.78

In [22]:
vendor_sales_summary['VendorName'] = vendor_sales_summary['VendorName'].str.strip()
#removing the wide space from vendor name

In [23]:
vendor_sales_summary.isnull().sum()
vendor_sales_summary['VendorName'].unique
vendor_sales_summary.fillna(0, inplace = True)
#Again checking the data after correcting the inconsistencies

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseAmount,TotalSalesQuantity,TotalSalesAmount,TotalSalesPrice,TotalExciseTax,TotalFreightCost
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080,3811251.60,142049.0,5101919.51,672819.31,260999.20,68601.68
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038,3804041.22,160247.0,4819073.49,561512.37,294438.66,144929.24
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407,3418303.68,187140.0,4538120.60,461140.15,343854.07,123780.22
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682,3261197.94,200412.0,4475972.88,420050.01,368242.80,257032.07
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,138109,3023206.01,135838.0,4223107.62,545778.28,249587.83,257032.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,4.99,750.0,2,2.64,5.0,15.95,10.96,0.55,27100.41
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,0.49,50.0,6,2.34,134.0,65.66,1.47,7.04,50293.62
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.74,0.99,50.0,2,1.48,2.0,1.98,0.99,0.10,14069.87
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.47,1.99,200.0,1,1.47,72.0,143.28,77.61,15.12,257032.07
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,0.99,50.0,1,0.71,86.0,85.14,33.66,4.46,38994.78

In [24]:
vendor_sales_summary['GrossProfit'] = vendor_sales_summary['TotalSalesAmount'] - vendor_sales_summary['TotalPurchaseAmount']
#Creating Gross Profit Aggregrate for further analysis
vendor_sales_summary['GrossProfit']

0        1290667.91
1        1015032.27
2        1119816.92
3        1214774.94
4        1199901.61
            ...
10687         13.31
10688         63.32
10689          0.50
10690        141.81
10691         84.43
Name: GrossProfit, Length: 10692, dtype: float64

In [25]:
vendor_sales_summary['ProfitMargin'] = (vendor_sales_summary['GrossProfit'] / vendor_sales_summary['TotalSalesAmount'])*100
#Creating ProfitMargin Aggregrate for further analysis

In [26]:
vendor_sales_summary['StockTurnover'] = vendor_sales_summary['TotalSalesQuantity']/vendor_sales_summary['TotalPurchaseQuantity']
#Creating StockTurnover Aggregrate for further analysis

In [27]:
vendor_sales_summary['TotalPurchaseRatio'] = vendor_sales_summary['TotalSalesAmount'] / vendor_sales_summary['TotalPurchaseAmount']
#Creating Total Purchase Ratio Aggregrate for further analysis

In [28]:
cursor = con.cursor()

In [29]:
vendor_sales_summary.columns

Index(['VendorNumber', 'VendorName', 'Brand', 'Description', 'PurchasePrice',
       'ActualPrice', 'Volume', 'TotalPurchaseQuantity', 'TotalPurchaseAmount',
       'TotalSalesQuantity', 'TotalSalesAmount', 'TotalSalesPrice',
       'TotalExciseTax', 'TotalFreightCost', 'GrossProfit', 'ProfitMargin',
       'StockTurnover', 'TotalPurchaseRatio'],
      dtype='str')

In [30]:
#Creating a Table to save the collected data into it.
cursor.execute("""Create Table if not exists vendor_sales_summary (
VendorNumber INT,
VendorName VARCHAR(100),
Brand INT,
Description VARCHAR(100),               
PurchasePrice DECIMAL (10,2),               
ActualPrice DECIMAL (10,2),               
Volume INT,
TotalPurchaseQuantity INT,
TotalPurchaseAmount DECIMAL(15,2),
TotalSalesQuantity INT,
TotalSalesAmount DECIMAL(15,2),
TotalSalesPrice DECIMAL(15,2),
TotalExciseTax DECIMAL(15,2),
TotalFreightCost DECIMAL(15,2),
GrossProfit DECIMAL(15,2),
ProfitMargin DECIMAL(15,2),
StockTurnover DECIMAL (15,2),
TotalPurchaseRatio DECIMAL (15,2),             
PRIMARY KEY (VendorNumber, Brand)              
);
""")

In [33]:
pd.read_sql_query("select * From vendor_sales_summary", con, index = False)

TypeError: read_sql_query() got an unexpected keyword argument 'index'

In [32]:
vendor_sales_summary.to_sql('vendor_sales_summary', con, if_exists = 'replace', index = False)

10692

In [ ]:
import sqlite3
import pandas as pd
import logging
from ingestion_db import ingest_db

logging.basicConfig(
filename = 'logs/get_vendor_summary.log',
level= logging.DEBUG,
format="%(asctime)s - %(levelname)s - %(message)s",
filemode= "a"
)

def  create_vendor_summary(con):
    '''this function will merge different table to get the overall vendor summary and adding new colum in resultant data'''
    vendor_sales_summary = pd.read_sql_query("""
    WITH FreightSummary AS 
    (
        SELECT 
            VendorNumber, 
            SUM(Freight) as TotalFreightCost 
        FROM vendor_invoice
        GROUP BY VendorNumber
    ),

    purchase_summary AS 
    (
        SELECT
            p.VendorNumber,
            p.VendorName,
            p.Brand,
            p.Description,
            p.PurchasePrice,
            pp.Volume,
            pp.Price as ActualPrice,
            SUM(p.Quantity) as TotalPurchaseQuantity,
            SUM(p.Dollars) as TotalPurchaseAmount
        FROM purchases p
        JOIN purchase_prices pp
            ON p.Brand = pp.Brand
        WHERE p.PurchasePrice > 0
        GROUP BY 
            p.VendorNumber, p.VendorName, p.Brand, 
            p.Description, p.PurchasePrice, 
            pp.Volume, pp.Price
    ),

    Sales_Summary AS 
    (
        SELECT
            VendorNo,
            Brand,
            SUM(SalesQuantity) as TotalSalesQuantity,
            SUM(SalesDollars) as TotalSalesAmount,
            SUM(SalesPrice) as TotalSalesPrice,
            SUM(ExciseTax) as TotalExciseTax
        FROM sales
        GROUP BY VendorNo, Brand
    )

    SELECT
        ps.VendorNumber,
        ps.VendorName,
        ps.Brand,
        ps.Description,
        ps.PurchasePrice,
        ps.ActualPrice,
        ps.Volume,
        ps.TotalPurchaseQuantity,
        ps.TotalPurchaseAmount,

        ss.TotalSalesQuantity,
        ss.TotalSalesAmount,
        ss.TotalSalesPrice,
        ss.TotalExciseTax,

        fs.TotalFreightCost

    FROM purchase_summary ps

    LEFT JOIN Sales_Summary ss
        ON ps.VendorNumber = ss.VendorNo
        AND ps.Brand = ss.Brand

    LEFT JOIN FreightSummary fs
        ON ps.VendorNumber = fs.VendorNumber

    ORDER BY ps.TotalPurchaseAmount DESC
    """, con)

    return vendor_sales_summary

def clean_data(df):
    '''this function will clean the data'''
    #changing data type to float
    df['Volume'] = df['Volume'].astype(float)

    #filling mssing values with 0
    df.fillna(0, inplace = True)

    #removing spaces form categorial columns
    df['VendorName'] = df['VendorName'].str.strip()

    #Creating New columns for better and additional analysis
    df['GrossProfit'] = df['TotalSalesAmount'] - df['TotalPurchaseAmount']
    df['ProfitMargin'] = (df['GrossProfit'] / df['TotalSalesAmount'])*100
    df['StockTurnover'] = df['TotalSalesQuantity']/df['TotalPurchaseQuantity']
    df['TotalPurchaseRatio'] = df['TotalSalesAmount'] / df['TotalPurchaseAmount']

    return df 

if __name__ == '__main__':
    #creating database connection
    con = sqlite3.connect('inventory.db')

    logging.info('creating Vendor Summary Table...')
    summary_df = create_vendor_summary(con)
    logging.info(summary_df.head())

    logging.info('cleaning data...')
    clean_df = clean_data(summary_df)
    logging.info(clean_df.head())

    logging.info('ingesting data....')
    ingest_db(clean_df, 'vendor_sales_summary', con)
    logging.info('Completed')